name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1155
          bb: 1.1.173
      - name: Run Babashka tests
        run: bb test-bb
      - name: Call run-tests-in-file-tree from bb
        run: bb test-bb-run-tests-in-file-tree
      - name: Run Clojure tests
        run: bb test-clj

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v1
        with: { java-version: 1.11 }

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: latest
          bb: latest

      - name: Build jar
        run: bb uber

      - name: Deploy to clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: bb deploy
